import { Globe } from "lucide-react"

export interface CurrencyData {
  country: string
  code: string
  symbol: string
  flag: string
  name: string
}

// Comprehensive currency data with country names, codes, symbols, flags, and names
export const CURRENCY_DATA: CurrencyData[] = [
  { country: "Afghanistan", code: "AFN", symbol: "؋", flag: "🇦🇫", name: "Afghan Afghani" },
  { country: "Albania", code: "ALL", symbol: "L", flag: "🇦🇱", name: "Albanian Lek" },
  { country: "Algeria", code: "DZD", symbol: "د.ج", flag: "🇩🇿", name: "Algerian Dinar" },
  { country: "Andorra", code: "EUR", symbol: "€", flag: "🇦🇩", name: "Euro" },
  { country: "Angola", code: "AOA", symbol: "Kz", flag: "🇦🇴", name: "Angolan Kwanza" },
  { country: "Antigua and Barbuda", code: "XCD", symbol: "$", flag: "🇦🇬", name: "East Caribbean Dollar" },
  { country: "Argentina", code: "ARS", symbol: "$", flag: "🇦🇷", name: "Argentine Peso" },
  { country: "Armenia", code: "AMD", symbol: "֏", flag: "🇦🇲", name: "Armenian Dram" },
  { country: "Australia", code: "AUD", symbol: "$", flag: "🇦🇺", name: "Australian Dollar" },
  { country: "Austria", code: "EUR", symbol: "€", flag: "🇦🇹", name: "Euro" },
  { country: "Azerbaijan", code: "AZN", symbol: "₼", flag: "🇦🇿", name: "Azerbaijani Manat" },
  { country: "Bahamas", code: "BSD", symbol: "$", flag: "🇧🇸", name: "Bahamian Dollar" },
  { country: "Bahrain", code: "BHD", symbol: "د.ب", flag: "🇧🇭", name: "Bahraini Dinar" },
  { country: "Bangladesh", code: "BDT", symbol: "৳", flag: "🇧🇩", name: "Bangladeshi Taka" },
  { country: "Barbados", code: "BBD", symbol: "$", flag: "🇧🇧", name: "Barbadian Dollar" },
  { country: "Belarus", code: "BYN", symbol: "Br", flag: "🇧🇾", name: "Belarusian Ruble" },
  { country: "Belgium", code: "EUR", symbol: "€", flag: "🇧🇪", name: "Euro" },
  { country: "Belize", code: "BZD", symbol: "$", flag: "🇧🇿", name: "Belize Dollar" },
  { country: "Benin", code: "XOF", symbol: "CFA", flag: "🇧🇯", name: "West African CFA Franc" },
  { country: "Bhutan", code: "BTN", symbol: "Nu", flag: "🇧🇹", name: "Bhutanese Ngultrum" },
  { country: "Bolivia", code: "BOB", symbol: "Bs", flag: "🇧🇴", name: "Bolivian Boliviano" },
  {
    country: "Bosnia and Herzegovina",
    code: "BAM",
    symbol: "KM",
    flag: "🇧🇦",
    name: "Bosnia-Herzegovina Convertible Mark",
  },
  { country: "Botswana", code: "BWP", symbol: "P", flag: "🇧🇼", name: "Botswanan Pula" },
  { country: "Brazil", code: "BRL", symbol: "R$", flag: "🇧🇷", name: "Brazilian Real" },
  { country: "Brunei", code: "BND", symbol: "B$", flag: "🇧🇳", name: "Brunei Dollar" },
  { country: "Bulgaria", code: "BGN", symbol: "лв", flag: "🇧🇬", name: "Bulgarian Lev" },
  { country: "Burkina Faso", code: "XOF", symbol: "CFA", flag: "🇧🇫", name: "West African CFA Franc" },
  { country: "Burundi", code: "BIF", symbol: "Fr", flag: "🇧🇮", name: "Burundian Franc" },
  { country: "Cabo Verde", code: "CVE", symbol: "Esc", flag: "🇨🇻", name: "Cape Verdean Escudo" },
  { country: "Cambodia", code: "KHR", symbol: "៛", flag: "🇰🇭", name: "Cambodian Riel" },
  { country: "Cameroon", code: "XAF", symbol: "CFA", flag: "🇨🇲", name: "Central African CFA Franc" },
  { country: "Canada", code: "CAD", symbol: "$", flag: "🇨🇦", name: "Canadian Dollar" },
  { country: "Central African Republic", code: "XAF", symbol: "CFA", flag: "🇨🇫", name: "Central African CFA Franc" },
  { country: "Chad", code: "XAF", symbol: "CFA", flag: "🇹🇩", name: "Central African CFA Franc" },
  { country: "Chile", code: "CLP", symbol: "$", flag: "🇨🇱", name: "Chilean Peso" },
  { country: "China", code: "CNY", symbol: "¥", flag: "🇨🇳", name: "Chinese Yuan" },
  { country: "Colombia", code: "COP", symbol: "$", flag: "🇨🇴", name: "Colombian Peso" },
  { country: "Comoros", code: "KMF", symbol: "Fr", flag: "🇰🇲", name: "Comorian Franc" },
  { country: "Congo, DR", code: "CDF", symbol: "Fr", flag: "🇨🇬", name: "Congolese Franc" },
  { country: "Congo, Republic", code: "XAF", symbol: "CFA", flag: "🇨🇬", name: "Central African CFA Franc" },
  { country: "Costa Rica", code: "CRC", symbol: "₡", flag: "🇨🇷", name: "Costa Rican Colón" },
  { country: "Côte d'Ivoire", code: "XOF", symbol: "CFA", flag: "🇨🇮", name: "West African CFA Franc" },
  { country: "Croatia", code: "HRK", symbol: "kn", flag: "🇭🇷", name: "Croatian Kuna" },
  { country: "Cuba", code: "CUP", symbol: "$", flag: "🇨🇺", name: "Cuban Peso" },
  { country: "Cyprus", code: "EUR", symbol: "€", flag: "🇨🇾", name: "Euro" },
  { country: "Czechia", code: "CZK", symbol: "Kč", flag: "🇨🇿", name: "Czech Koruna" },
  { country: "Denmark", code: "DKK", symbol: "kr", flag: "🇩🇰", name: "Danish Krone" },
  { country: "Djibouti", code: "DJF", symbol: "Fr", flag: "🇩🇯", name: "Djiboutian Franc" },
  { country: "Dominica", code: "XCD", symbol: "$", flag: "🇩🇲", name: "East Caribbean Dollar" },
  { country: "Dominican Republic", code: "DOP", symbol: "$", flag: "🇩🇴", name: "Dominican Peso" },
  { country: "Ecuador", code: "USD", symbol: "$", flag: "🇪🇨", name: "US Dollar" },
  { country: "Egypt", code: "EGP", symbol: "ج.م", flag: "🇪🇬", name: "Egyptian Pound" },
  { country: "El Salvador", code: "USD", symbol: "$", flag: "🇸🇻", name: "US Dollar" },
  { country: "Equatorial Guinea", code: "XAF", symbol: "CFA", flag: "🇬🇶", name: "Central African CFA Franc" },
  { country: "Eritrea", code: "ERN", symbol: "Nfk", flag: "🇪🇷", name: "Eritrean Nakfa" },
  { country: "Estonia", code: "EUR", symbol: "€", flag: "🇪🇪", name: "Euro" },
  { country: "Eswatini", code: "SZL", symbol: "L", flag: "🇸🇿", name: "Swazi Lilangeni" },
  { country: "Ethiopia", code: "ETB", symbol: "Br", flag: "🇪🇹", name: "Ethiopian Birr" },
  { country: "Fiji", code: "FJD", symbol: "$", flag: "🇫🇯", name: "Fijian Dollar" },
  { country: "Finland", code: "EUR", symbol: "€", flag: "🇫🇮", name: "Euro" },
  { country: "France", code: "EUR", symbol: "€", flag: "🇫🇷", name: "Euro" },
  { country: "Gabon", code: "XAF", symbol: "CFA", flag: "🇬🇦", name: "Central African CFA Franc" },
  { country: "Gambia", code: "GMD", symbol: "D", flag: "🇬🇲", name: "Gambian Dalasi" },
  { country: "Georgia", code: "GEL", symbol: "₾", flag: "🇬🇪", name: "Georgian Lari" },
  { country: "Germany", code: "EUR", symbol: "€", flag: "🇩🇪", name: "Euro" },
  { country: "Ghana", code: "GHS", symbol: "₵", flag: "🇬🇭", name: "Ghanaian Cedi" },
  { country: "Greece", code: "EUR", symbol: "€", flag: "🇬🇷", name: "Euro" },
  { country: "Grenada", code: "XCD", symbol: "$", flag: "🇬🇩", name: "East Caribbean Dollar" },
  { country: "Guatemala", code: "GTQ", symbol: "Q", flag: "🇬🇹", name: "Guatemalan Quetzal" },
  { country: "Guinea", code: "GNF", symbol: "Fr", flag: "🇬🇳", name: "Guinean Franc" },
  { country: "Guinea-Bissau", code: "XOF", symbol: "CFA", flag: "🇬🇼", name: "West African CFA Franc" },
  { country: "Guyana", code: "GYD", symbol: "$", flag: "🇬🇾", name: "Guyanese Dollar" },
  { country: "Haiti", code: "HTG", symbol: "G", flag: "🇭🇹", name: "Haitian Gourde" },
  { country: "Honduras", code: "HNL", symbol: "L", flag: "🇭🇳", name: "Honduran Lempira" },
  { country: "Hungary", code: "HUF", symbol: "Ft", flag: "🇭🇺", name: "Hungarian Forint" },
  { country: "Iceland", code: "ISK", symbol: "kr", flag: "🇮🇸", name: "Icelandic Króna" },
  { country: "India", code: "INR", symbol: "₹", flag: "🇮🇳", name: "Indian Rupee" },
  { country: "Indonesia", code: "IDR", symbol: "Rp", flag: "🇮🇩", name: "Indonesian Rupiah" },
  { country: "Iran", code: "IRR", symbol: "﷼", flag: "🇮🇷", name: "Iranian Rial" },
  { country: "Iraq", code: "IQD", symbol: "ع.د", flag: "🇮🇶", name: "Iraqi Dinar" },
  { country: "Ireland", code: "EUR", symbol: "€", flag: "🇮🇪", name: "Euro" },
  { country: "Israel", code: "ILS", symbol: "₪", flag: "🇮🇱", name: "Israeli New Shekel" },
  { country: "Italy", code: "EUR", symbol: "€", flag: "🇮🇹", name: "Euro" },
  { country: "Jamaica", code: "JMD", symbol: "$", flag: "🇯🇲", name: "Jamaican Dollar" },
  { country: "Japan", code: "JPY", symbol: "¥", flag: "🇯🇵", name: "Japanese Yen" },
  { country: "Jordan", code: "JOD", symbol: "د.ا", flag: "🇯🇴", name: "Jordanian Dinar" },
  { country: "Kazakhstan", code: "KZT", symbol: "₸", flag: "🇰🇿", name: "Kazakhstani Tenge" },
  { country: "Kenya", code: "KES", symbol: "Sh", flag: "🇰🇪", name: "Kenyan Shilling" },
  { country: "Kiribati", code: "AUD", symbol: "$", flag: "🇰🇮", name: "Australian Dollar" },
  { country: "Korea, North", code: "KPW", symbol: "₩", flag: "🇰🇵", name: "North Korean Won" },
  { country: "Korea, South", code: "KRW", symbol: "₩", flag: "🇰🇷", name: "South Korean Won" },
  { country: "Kosovo", code: "EUR", symbol: "€", flag: "🇽🇰", name: "Euro" },
  { country: "Kuwait", code: "KWD", symbol: "د.ك", flag: "🇰🇼", name: "Kuwaiti Dinar" },
  { country: "Kyrgyzstan", code: "KGS", symbol: "сом", flag: "🇰🇬", name: "Kyrgystani Som" },
  { country: "Laos", code: "LAK", symbol: "₭", flag: "🇱🇦", name: "Lao Kip" },
  { country: "Latvia", code: "EUR", symbol: "€", flag: "🇱🇻", name: "Euro" },
  { country: "Lebanon", code: "LBP", symbol: "ل.ل", flag: "🇱🇧", name: "Lebanese Pound" },
  { country: "Lesotho", code: "LSL", symbol: "L", flag: "🇱🇸", name: "Lesotho Loti" },
  { country: "Liberia", code: "LRD", symbol: "$", flag: "🇱🇷", name: "Liberian Dollar" },
  { country: "Libya", code: "LYD", symbol: "ل.د", flag: "🇱🇾", name: "Libyan Dinar" },
  { country: "Liechtenstein", code: "CHF", symbol: "Fr", flag: "🇱🇮", name: "Swiss Franc" },
  { country: "Lithuania", code: "EUR", symbol: "€", flag: "🇱🇹", name: "Euro" },
  { country: "Luxembourg", code: "EUR", symbol: "€", flag: "🇱🇺", name: "Euro" },
  { country: "Madagascar", code: "MGA", symbol: "Ar", flag: "🇲🇬", name: "Malagasy Ariary" },
  { country: "Malawi", code: "MWK", symbol: "K", flag: "🇲🇼", name: "Malawian Kwacha" },
  { country: "Malaysia", code: "MYR", symbol: "RM", flag: "🇲🇾", name: "Malaysian Ringgit" },
  { country: "Maldives", code: "MVR", symbol: ".", flag: "🇲🇻", name: "Maldivian Rufiyaa" },
  { country: "Mali", code: "XOF", symbol: "CFA", flag: "🇲🇱", name: "West African CFA Franc" },
  { country: "Malta", code: "EUR", symbol: "€", flag: "🇲🇹", name: "Euro" },
  { country: "Marshall Islands", code: "USD", symbol: "$", flag: "🇲🇭", name: "US Dollar" },
  { country: "Mauritania", code: "MRU", symbol: "UM", flag: "🇲🇷", name: "Mauritanian Ouguiya" },
  { country: "Mauritius", code: "MUR", symbol: "₨", flag: "🇲🇺", name: "Mauritian Rupee" },
  { country: "Mexico", code: "MXN", symbol: "$", flag: "🇲🇽", name: "Mexican Peso" },
  { country: "Micronesia", code: "USD", symbol: "$", flag: "🇫🇲", name: "US Dollar" },
  { country: "Moldova", code: "MDL", symbol: "Lei", flag: "🇲🇩", name: "Moldovan Leu" },
  { country: "Monaco", code: "EUR", symbol: "€", flag: "🇲🇨", name: "Euro" },
  { country: "Mongolia", code: "MNT", symbol: "₮", flag: "🇲🇳", name: "Mongolian Tugrik" },
  { country: "Montenegro", code: "EUR", symbol: "€", flag: "🇲🇪", name: "Euro" },
  { country: "Morocco", code: "MAD", symbol: "د.م.", flag: "🇲🇦", name: "Moroccan Dirham" },
  { country: "Mozambique", code: "MZN", symbol: "MT", flag: "🇲🇿", name: "Mozambican Metical" },
  { country: "Myanmar", code: "MMK", symbol: "Ks", flag: "🇲🇲", name: "Myanmar Kyat" },
  { country: "Namibia", code: "NAD", symbol: "$", flag: "🇳🇦", name: "Namibian Dollar" },
  { country: "Nauru", code: "AUD", symbol: "$", flag: "🇳🇷", name: "Australian Dollar" },
  { country: "Nepal", code: "NPR", symbol: "₨", flag: "🇳🇵", name: "Nepalese Rupee" },
  { country: "Netherlands", code: "EUR", symbol: "€", flag: "🇳🇱", name: "Euro" },
  { country: "New Zealand", code: "NZD", symbol: "$", flag: "🇳🇿", name: "New Zealand Dollar" },
  { country: "Nicaragua", code: "NIO", symbol: "C$", flag: "🇳🇮", name: "Nicaraguan Córdoba" },
  { country: "Niger", code: "XOF", symbol: "CFA", flag: "🇳🇪", name: "West African CFA Franc" },
  { country: "Nigeria", code: "NGN", symbol: "₦", flag: "🇳🇬", name: "Nigerian Naira" },
  { country: "North Macedonia", code: "MKD", symbol: "ден", flag: "🇲🇰", name: "Macedonian Denar" },
  { country: "Norway", code: "NOK", symbol: "kr", flag: "🇳🇴", name: "Norwegian Krone" },
  { country: "Oman", code: "OMR", symbol: "ر.ع.", flag: "🇴🇲", name: "Omani Rial" },
  { country: "Pakistan", code: "PKR", symbol: "₨", flag: "🇵🇰", name: "Pakistani Rupee" },
  { country: "Palau", code: "USD", symbol: "$", flag: "🇵🇼", name: "US Dollar" },
  { country: "Panama", code: "PAB", symbol: "B/.", flag: "🇵🇦", name: "Panamanian Balboa" },
  { country: "Papua New Guinea", code: "PGK", symbol: "K", flag: "🇵🇬", name: "Papua New Guinean Kina" },
  { country: "Paraguay", code: "PYG", symbol: "₲", flag: "🇵🇾", name: "Paraguayan Guarani" },
  { country: "Peru", code: "PEN", symbol: "S/.", flag: "🇵🇪", name: "Peruvian Sol" },
  { country: "Philippines", code: "PHP", symbol: "₱", flag: "🇵🇭", name: "Philippine Peso" },
  { country: "Poland", code: "PLN", symbol: "zł", flag: "🇵🇱", name: "Polish Złoty" },
  { country: "Portugal", code: "EUR", symbol: "€", flag: "🇵🇹", name: "Euro" },
  { country: "Qatar", code: "QAR", symbol: "ر.ق", flag: "🇶🇦", name: "Qatari Riyal" },
  { country: "Romania", code: "RON", symbol: "lei", flag: "🇷🇴", name: "Romanian Leu" },
  { country: "Russia", code: "RUB", symbol: "₽", flag: "🇷🇺", name: "Russian Ruble" },
  { country: "Rwanda", code: "RWF", symbol: "Fr", flag: "🇷🇼", name: "Rwandan Franc" },
  { country: "Saint Kitts and Nevis", code: "XCD", symbol: "$", flag: "🇰🇳", name: "East Caribbean Dollar" },
  { country: "Saint Lucia", code: "XCD", symbol: "$", flag: "🇱🇨", name: "East Caribbean Dollar" },
  { country: "Saint Vincent and the Grenadines", code: "XCD", symbol: "$", flag: "🇻🇨", name: "East Caribbean Dollar" },
  { country: "Samoa", code: "WST", symbol: "T", flag: "🇼🇸", name: "Samoan Tala" },
  { country: "San Marino", code: "EUR", symbol: "€", flag: "🇸🇲", name: "Euro" },
  { country: "Sao Tome and Principe", code: "STN", symbol: "Db", flag: "🇸🇹", name: "São Tomé and Príncipe Dobra" },
  { country: "Saudi Arabia", code: "SAR", symbol: "ر.س", flag: "🇸🇦", name: "Saudi Riyal" },
  { country: "Senegal", code: "XOF", symbol: "CFA", flag: "🇸🇳", name: "West African CFA Franc" },
  { country: "Serbia", code: "RSD", symbol: "дин", flag: "🇷🇸", name: "Serbian Dinar" },
  { country: "Seychelles", code: "SCR", symbol: "₨", flag: "🇸🇨", name: "Seychellois Rupee" },
  { country: "Sierra Leone", code: "SLL", symbol: "Le", flag: "🇸🇱", name: "Sierra Leonean Leone" },
  { country: "Singapore", code: "SGD", symbol: "$", flag: "🇸🇬", name: "Singapore Dollar" },
  { country: "Slovakia", code: "EUR", symbol: "€", flag: "🇸🇰", name: "Euro" },
  { country: "Slovenia", code: "EUR", symbol: "€", flag: "🇸🇮", name: "Euro" },
  { country: "Solomon Islands", code: "SBD", symbol: "$", flag: "🇸🇧", name: "Solomon Islands Dollar" },
  { country: "Somalia", code: "SOS", symbol: "Sh", flag: "🇸🇴", name: "Somali Shilling" },
  { country: "South Africa", code: "ZAR", symbol: "R", flag: "🇿🇦", name: "South African Rand" },
  { country: "South Sudan", code: "SSP", symbol: "£", flag: "🇸🇸", name: "South Sudanese Pound" },
  { country: "Spain", code: "EUR", symbol: "€", flag: "🇪🇸", name: "Euro" },
  { country: "Sri Lanka", code: "LKR", symbol: "Rs", flag: "🇱🇰", name: "Sri Lankan Rupee" },
  { country: "Sudan", code: "SDG", symbol: "ج.س", flag: "🇸🇩", name: "Sudanese Pound" },
  { country: "Suriname", code: "SRD", symbol: "$", flag: "🇸🇷", name: "Surinamese Dollar" },
  { country: "Sweden", code: "SEK", symbol: "kr", flag: "🇸🇪", name: "Swedish Krona" },
  { country: "Switzerland", code: "CHF", symbol: "Fr", flag: "🇨🇭", name: "Swiss Franc" },
  { country: "Syria", code: "SYP", symbol: "ل.س", flag: "🇸🇾", name: "Syrian Pound" },
  { country: "Taiwan", code: "TWD", symbol: "NT$", flag: "🇹🇼", name: "New Taiwan Dollar" },
  { country: "Tajikistan", code: "TJS", symbol: "SM", flag: "🇹🇯", name: "Tajikistani Somoni" },
  { country: "Tanzania", code: "TZS", symbol: "Sh", flag: "🇹🇿", name: "Tanzanian Shilling" },
  { country: "Thailand", code: "THB", symbol: "฿", flag: "🇹🇭", name: "Thai Baht" },
  { country: "Timor-Leste", code: "USD", symbol: "$", flag: "🇹🇱", name: "US Dollar" },
  { country: "Togo", code: "XOF", symbol: "CFA", flag: "🇹🇬", name: "West African CFA Franc" },
  { country: "Tonga", code: "TOP", symbol: "T$", flag: "🇹🇴", name: "Tongan Paʻanga" },
  { country: "Trinidad and Tobago", code: "TTD", symbol: "$", flag: "🇹🇹", name: "Trinidad and Tobago Dollar" },
  { country: "Tunisia", code: "TND", symbol: "د.ت", flag: "🇹🇳", name: "Tunisian Dinar" },
  { country: "Turkey", code: "TRY", symbol: "₺", flag: "🇹🇷", name: "Turkish Lira" },
  { country: "Turkmenistan", code: "TMT", symbol: "T", flag: "🇹🇲", name: "Turkmenistani Manat" },
  { country: "Tuvalu", code: "AUD", symbol: "$", flag: "🇹🇻", name: "Australian Dollar" },
  { country: "Uganda", code: "UGX", symbol: "Sh", flag: "🇺🇬", name: "Ugandan Shilling" },
  { country: "Ukraine", code: "UAH", symbol: "₴", flag: "🇺🇦", name: "Ukrainian Hryvnia" },
  { country: "United Arab Emirates", code: "AED", symbol: "د.إ", flag: "🇦🇪", name: "United Arab Emirates Dirham" },
  { country: "United Kingdom", code: "GBP", symbol: "£", flag: "🇬🇧", name: "British Pound" },
  { country: "United States", code: "USD", symbol: "$", flag: "🇺🇸", name: "US Dollar" },
  { country: "Uruguay", code: "UYU", symbol: "$", flag: "🇺🇾", name: "Uruguayan Peso" },
  { country: "Uzbekistan", code: "UZS", symbol: "сўм", flag: "🇺🇿", name: "Uzbekistani Som" },
  { country: "Vanuatu", code: "VUV", symbol: "Vt", flag: "🇻🇺", name: "Vanuatu Vatu" },
  { country: "Vatican City", code: "EUR", symbol: "€", flag: "🇻🇦", name: "Euro" },
  { country: "Venezuela", code: "VEF", symbol: "Bs.S", flag: "🇻🇪", name: "Venezuelan Bolívar" },
  { country: "Vietnam", code: "VND", symbol: "₫", flag: "🇻🇳", name: "Vietnamese Đồng" },
  { country: "Yemen", code: "YER", symbol: "﷼", flag: "🇾🇪", name: "Yemeni Rial" },
  { country: "Zambia", code: "ZMW", symbol: "ZK", flag: "🇿🇲", name: "Zambian Kwacha" },
  { country: "Zimbabwe", code: "ZWL", symbol: "Z$", flag: "🇿🇼", name: "Zimbabwean Dollar" },
]

// All currency codes for easy access
export const CURRENCY_CODES: string[] = CURRENCY_DATA.map((currency) => currency.code)

// Popular currencies for quick selection
export const POPULAR_CURRENCIES = ["USD", "EUR", "GBP", "JPY", "CAD", "AUD", "CHF", "CNY", "INR"]

// Function to get currency details by code
export const getCurrencyByCode = (code: string): CurrencyData | undefined => {
  return CURRENCY_DATA.find((currency) => currency.code === code)
}

// Function to search currencies by query
export const searchCurrencies = (query: string): CurrencyData[] => {
  if (!query) return CURRENCY_DATA

  const lowerQuery = query.toLowerCase()
  return CURRENCY_DATA.filter(
    (currency) =>
      currency.country.toLowerCase().includes(lowerQuery) ||
      currency.code.toLowerCase().includes(lowerQuery) ||
      currency.name.toLowerCase().includes(lowerQuery) ||
      currency.symbol.toLowerCase().includes(lowerQuery),
  )
}

// Default currency icon component
export const CurrencyIcon = () => <Globe className="h-4 w-4" />
